version: 3
name: KrakenD with Keycloak JWT & OTEL

extra_config:
  telemetry/opentelemetry:
    service_name: krakend-gateway
    deploy_env: development
    metric_reporting_period: 5
    exporters:
      otlp:
        - name: otlp_exporter
          host: jaeger
          port: 4318
          disable_metrics: true
          disable_traces: false
          insecure: true
          use_http: true
    layers:
      global:
        disable_metrics: true
        disable_traces: true
        disable_propagation: false
      proxy:
        disable_metrics: true
        disable_traces: true
        disable_propagation: false
      backend:
        traces:
          round_trip: true
          disable_stage: false
          read_payload: true
          detailed_connection: true

endpoints:
  - endpoint: /user/v1/registration
    method: POST
    output_encoding: no-op
    backend:
      - host: http://api:8080
        url_pattern: /user/v1/registration

  - endpoint: /user/v1/verifications/{id}/preflight
    input_query_strings:
      - token
    method: GET
    output_encoding: no-op
    backend:
      - host: http://api:8080
        url_pattern: /user/v1/verifications/{id}/preflight
        input_query_strings:
          - token

  - endpoint: /user/v1/verifications/{id}/password-setup
    method: POST
    output_encoding: no-op
    backend:
      - host: http://api:8080
        url_pattern: /user/v1/verifications/{id}/password-setup

  - endpoint: /user/v1/me
    method: GET
    output_encoding: no-op
    input_headers:
      - x-idp-user-id
      - x-app-user-id
    backend:
      - host: http://api:8080
        url_pattern: /user/v1/me
        input_headers:
          - x-idp-user-id
          - x-app-user-id
    extra_config:
      auth/validator:
        alg: RS256
        jwk_url: http://keycloak:8081/realms/app/protocol/openid-connect/certs
        disable_jwk_security: true
        cache: false
        issuer: http://localhost:8081/realms/app
        operation_debug: true
        propagate_claims:
          - ["sub", "x-idp-user-id"]
          - ["app_user_id", "x-app-user-id"]

