root = "."
tmp_dir = "/tmp"

[build]
  cmd = "go build -o /tmp/api ./cmd/api"
  bin = "/tmp/api"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000

[log]
  time = true
  color = true
  level = "debug"
