version: 3

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

exclude:
  - bin
  - cmd
  - ent
  - mock

components:
  # Application Core layers
  # TODO fix naming mismatch - core/activity/domain and NOT core/domain/activity
  core/domain/activity:
    in: internal/core/component/activity/domain/**
  core/domain/attendance:
    in: internal/core/component/attendance/domain/**
  core/domain/user:
    in: internal/core/component/user/domain/**
  core/application/activity:
    in: internal/core/component/activity/application/**
  core/application/attendance:
    in: internal/core/component/attendance/application/**
  core/application/user:
    in: internal/core/component/user/application/**
  core/ports:
    in: internal/core/port/**
  core/shared_kernel:
    in: internal/core/shared_kernel/**
  # Outer layers
  presentation:
    # TODO introduce separate api and web layers. Make web not depending on anything but config
    in: internal/presentation/**
  infrastructure:
    in:
      - internal/infrastructure/**
      - config/**
  # Composition root/boilerplate
  bootstrap:
    in:
      - bootstrap/**
      - database/**

deps:
  core/domain/activity:
    mayDependOn:
      - core/domain/activity # self
      - core/shared_kernel
  core/domain/attendance:
    mayDependOn:
      - core/domain/attendance # self
      - core/shared_kernel
  core/domain/user:
    mayDependOn:
      - core/domain/user # self
      - core/shared_kernel
  core/application/activity:
    mayDependOn:
      - core/application/activity # self
      - core/domain/activity
      - core/ports
      - core/shared_kernel
  core/application/attendance:
    mayDependOn:
      - core/application/attendance # self
      - core/domain/attendance
      - core/ports
      - core/shared_kernel
  core/application/user:
    mayDependOn:
      - core/application/user # self
      - core/domain/user
      - core/ports
      - core/shared_kernel
  core/ports:
    mayDependOn:
      - core/ports # self
      - core/shared_kernel
  core/shared_kernel:
    mayDependOn:
      - core/shared_kernel # self
  presentation:
    anyVendorDeps: true
    mayDependOn:
      - presentation # self
      - infrastructure
      - core/ports
      - core/shared_kernel
      # activity
      - core/domain/activity
      - core/application/activity
      # attendance
      - core/domain/attendance
      - core/application/attendance
      # user
      - core/domain/user
      - core/application/user
  infrastructure:
    deepScan: false
    anyVendorDeps: true
    mayDependOn:
      - infrastructure # self
      - core/ports
      - core/shared_kernel
      # activity
      - core/domain/activity
      - core/application/activity
      # attendance
      - core/domain/attendance
      - core/application/attendance
      # user
      - core/domain/user
      - core/application/user
  bootstrap:
    deepScan: false
    anyVendorDeps: true
    anyProjectDeps: true
