profile: cover.out

# Holds coverage thresholds percentages, values should be in range [0-100].
threshold:
  file: 100
  package: 100
  total: 100

exclude:
  paths:
    - ^bootstrap
    - ^cmd
    - ^config
    - ^database
    - ^internal/infrastructure/observability
    - ^internal/infrastructure/persistence/ent/generated
    - ^mock
    # TODO remove after testing these
    - ^internal/infrastructure/observability/otel/middleware
    - ^internal/infrastructure/persistence/ent/activity
    - ^internal/infrastructure/persistence/ent/attendance
    - ^internal/infrastructure/persistence/pgsql
    - ^internal/infrastructure/observability/otel
