coverage:
  status:
    project:
      default:
        target: 100%
  ignore:
    - "bootstrap/*"
    - "cmd/*"
    - "config/*"
    - "database/ent/*"
    - "internal/infrastructure/persistence/ent/generated/*"
    - "internal/infrastructure/persistence/ent/activity/migrate.go"
    - "internal/infrastructure/persistence/ent/attendance/migrate.go"
    - "internal/infrastructure/bootstrap/*"
    - "mock/*"