coverage:
  status:
    project:
      default:
        target: 100%
  ignore:
    - "^cmd/"
    - "^ent/"
    - "^config/"
    - "^internal/infrastructure/persistence/ent/generated/"
    - "^internal/infrastructure/bootstrap/"
    - "^mock/"
