x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"

x-backend-api-environment: &x-backend-api-environment
  # App settings
  APP_NAME: "activity-planner-api"
  ZAP_DEV_MODE: true

  ### Databases

  # Activity context
  DB_ACTIVITY_DRIVER: "postgres"
  DB_ACTIVITY_HOST: "db"
  DB_ACTIVITY_PORT: "5432"
  DB_ACTIVITY_USER: "user"
  DB_ACTIVITY_PASSWORD: "password"
  DB_ACTIVITY_DATABASE: "activity"
  DB_ACTIVITY_SSLMODE: "disable"

  # Attendance context
  DB_ATTENDANCE_DRIVER: "postgres"
  DB_ATTENDANCE_HOST: "db"
  DB_ATTENDANCE_PORT: "5432"
  DB_ATTENDANCE_USER: "user"
  DB_ATTENDANCE_PASSWORD: "password"
  DB_ATTENDANCE_DATABASE: "attendance"
  DB_ATTENDANCE_SSLMODE: "disable"

  # User context
  DB_USER_DRIVER: "postgres"
  DB_USER_HOST: "db"
  DB_USER_PORT: "5432"
  DB_USER_USER: "user"
  DB_USER_PASSWORD: "password"
  DB_USER_DATABASE: "user"
  DB_USER_SSLMODE: "disable"

  # Keycloak
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_OAUTH_CLIENT_ID: "user-admin"
  KEYCLOAK_OAUTH_CLIENT_SECRET: "secret"

  # Mail
  MAIL_HOST: "mailhog"
  MAIL_PORT: 1025
  MAIL_USER: ""
  MAIL_PASSWORD: ""

  # Frontend
  FRONTEND_WEB_URL: "http://localhost:8079"

  # Go
  GO111MODULE: on

  # Tracing
  TRACE_ENDPOINT: "jaeger:4318"

  # OTEL
  OTEL_LOG_LEVEL: "debug"
  OTEL_EXPORTER_JAEGER_LOG_SPANS: true

x-backend-web-environment: &x-backend-web-environment
  # App settings
  APP_NAME: "activity-planner-web"
  ZAP_DEV_MODE: true

  # Keycloak
  KEYCLOAK_HOST: "http://localhost:8081"
  KEYCLOAK_OAUTH_CLIENT_ID: "web-app"
  KEYCLOAK_REDIRECT_URI: "http://localhost:8079/oauth2/callback"

  # Activity planner API
  API_HOST: "http://krakend:8080"

  # Go
  GO111MODULE: on

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 5s
      retries: 5
    networks:
      app_network:
        aliases:
          - db.lvh.me
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      <<: *x-backend-api-environment
    command: air -c .air.api.toml
    ports:
      - "8080:8080"
    depends_on:
      - db
      - jaeger
    networks:
      app_network:
        aliases:
          - api.lvh.me
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      <<: *x-backend-web-environment
    command: air -c .air.web.toml
    ports:
      - "8079:8080"
    depends_on:
      - krakend
    networks:
      app_network:
        aliases:
          - web.lvh.me

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"        # Jaeger UI
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      app_network:
        aliases:
          - jaeger.lvh.me

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command:
      - start-dev
      - --import-realm
      - --db=postgres
      - --db-url-host=db
      - --db-url-port=5432
      - --db-url-database=keycloak
      - --db-username=user
      - --db-password=password
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    depends_on:
      - db
    ports:
      - "8081:8080"
    volumes:
      - ./config/keycloak/realms:/opt/keycloak/data/import:ro
      - ./config/keycloak/themes:/opt/keycloak/themes:ro
    networks:
      app_network:
        aliases:
          - auth.lvh.me

  krakend:
    image: krakend:2.10
    command: ["krakend", "run", "-c", "/etc/krakend/krakend.yaml"]
    ports:
      - "8000:8080"
    volumes:
      - ./config/krakend/krakend.yaml:/etc/krakend/krakend.yaml:ro
    networks:
      app_network:
        aliases:
          - krakend.lvh.me

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      app_network:
        aliases:
          - mailhog.lvh.me

#  app:
#    container_name: app
#    platform: linux/amd64
#    pid: "host"
#    build:
#      context: .
#    environment:
#      <<: *x-backend-app-environment
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    depends_on:
#      - db
#    networks:
#      app_network:
#        aliases:
#          - app.lvh.me

networks:
  app_network:
    external: false


volumes:
  db_data:
