x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"

x-backend-app-environment: &x-backend-app-environment
  # Database
  DB_DRIVER: "postgres"

  # Postgres
  PG_POOL_MAX: "2"
  PG_URL: "postgres://user:password@db:5432/db?sslmode=disable"
  # Go
  GO111MODULE: on

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      retries: 5
    networks:
      app_network:
        aliases:
          - db.lvh.me
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      <<: *x-backend-app-environment
    command: air
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - app.lvh.me
#  app:
#    container_name: app
#    platform: linux/amd64
#    pid: "host"
#    build:
#      context: .
#    environment:
#      <<: *x-backend-app-environment
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    depends_on:
#      - db
#    networks:
#      app_network:
#        aliases:
#          - app.lvh.me

networks:
  app_network:
    external: false


volumes:
  db_data:
