# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Install go-arch-lint
      run: |
        GO111MODULE=on go install github.com/fe3dback/go-arch-lint@latest
        echo "$GOPATH/bin" >> $GITHUB_PATH
  
    - name: Check Architecture Layers
      run: go-arch-lint check

    - name: Run unit tests (with coverage)
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Unit tests - check thresholds
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml
        git-token: ${{ github.ref_name == 'master' && secrets.GITHUB_TOKEN || '' }}
        git-branch: coverage-badges
#
#    - name: Test
#      run: go test -coverprofile=coverage.txt -v ./...
#
#    - name: Upload coverage reports to Codecov
#      uses: codecov/codecov-action@v5
#      with:
#        fail_ci_if_error: true
#        verbose: true
#        token: ${{ secrets.CODECOV_TOKEN }}
